name: 2- ğŸ¦‘ Multi OS & Versions

on:
  push:
    branches: [ "demo-ci" ]

  workflow_dispatch:

jobs:
    exemple_multi_version:
        name: ğŸ™ Use many os & node versions
        strategy:
          # continuer Ã  excuter les autres workflow si un Ã©choue !!! :)
          fail-fast: false 
          matrix:
            os: [windows-latest, ubuntu-latest]
            node: [12, 14, 16]
            include:
              - os: windows-latest
                node: 16
                npm: 6

        runs-on: ${{ matrix.os }}
        steps:
          - name: âš™ï¸ Setup node
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node }}
        
          - name: ğŸ”§ only install on windows & node version is 16
            if: ${{ matrix.npm }}
            run: npm install -g npm@${{ matrix.npm }}

          - name: ğŸ‘€ Read npm version 
            run: npm --version

          - name: ğŸ”– Read node version 
            run: node -v