name: 1- ğŸ” Get Started

on:
  push:
    branches: ["demo-test-27"]

  workflow_dispatch:
env:
  IS_OK: false

jobs:
  build:
    name: ğŸ³ Build

    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘Ÿ Run a one-line script
        if: ${{ env.IS_OK == 'true' && success() }}
        run: echo Hello world ğŸ˜!

      - name: ğŸ›‘ This is the "else" part
        if: ${{ env.IS_OK == 'false' || failure() }}
        # run: |
        #     echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
        #     exit 1
        uses: actions/github-script@v3
        with:
            script: |
                core.setFailed('Il y eu une erreur, IS_OK est false!')