name: 1- ğŸ” Get Started

on:
  push:
    branches: ["demo-test-27"]

  workflow_dispatch:
env:
  IS_OK: false

jobs:
  build:
    name: ğŸ³ Build

    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘Ÿ Run a one-line script
        if: ${{ env.IS_OK == 'false' && success() }}
        run: echo Hello world ğŸ˜!
