name: 1- ğŸ” Get Started

on:
  push:
    branches: ["demo-test-27"]

  workflow_dispatch:
env:
  IS_OK: false

jobs:
  build:
    name: ğŸ³ Build

    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘Ÿ Run a one-line script
        if: ${{ env.IS_OK == 'true' && success() }}
        run: echo Hello world ğŸ˜!

      - name: ğŸ›‘ This is the "else" part
        if: ${{ env.IS_OK == 'false' || failure() }}
        run: | 
            echo The condition was not met.
            error "An error occurred in this step."
        